#!/bin/bash
# aescrypt - a script to encrypt/decrypt files using OpenSSL

show_usage () {
  echo "usage: aescrypt [-d] <infile> <outfile>" 1>&2
}

PNAME=`basename $0`

if [[ "$PNAME" != "aescrypt" ]]; then
  show_usage
  exit 1;
fi

if [[ "$1" == "-d" ]]; then
  DECRYPT="YES"
  IFNAME=$2
  OFNAME=$3
else
  DECRYPT="NO"
  IFNAME=$1
  OFNAME=$2
fi

# echo "[DEBUG]" IFNAME is "$IFNAME"
# echo "[DEBUG]" OFNAME is "$OFNAME"

if [[ -z "$IFNAME" ]] || [[ -z "$OFNAME" ]]; then
  show_usage
  exit 1;
fi

if [[ "$IFNAME" = "$OFNAME" ]]; then
  echo "error: input file and output file cannot be the same file" 1>&2
  exit 1;
fi

if [ "$DECRYPT" = "NO" ]; then
  openssl aes-256-cbc -a -md sha512 -pbkdf2 -iter 100000 -salt -in "$IFNAME" -out "$OFNAME"
else
  openssl aes-256-cbc -d -a -md sha512 -pbkdf2 -iter 100000 -salt -in "$IFNAME" -out "$OFNAME"
fi
