#!/bin/sh

if [ $# -eq 1 ]
  then

    if [ -e "$1" ]
      then
        echo "chown -R root:wheel $1"
        chown -R root:wheel "$1"

        echo "find $1 -type f -print0 | xargs -0 chmod 444"
        find "$1" -type f -print0 | xargs -0 chmod 444

        echo "find $1 -type d -print0 | xargs -0 chmod 555"
        find "$1" -type d -print0 | xargs -0 chmod 555
    else
        echo `basename "$0"`: "$1": No such file or directory
    fi

else
    echo `basename "$0"`: error: Invalid argument
fi

